apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
data:
  SECRET_KEY: "QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK" # base64 encoded '@e2(yx)v&tgh3_s=0yja-h!dpebxsz~dg47x)-k&kq_3zf*9e*'
  NAME: "dG9kb2FwcGRiCg==" # base64 encoded 'todoappdb'
  USER: "dXNlcgo=" # base64 encoded 'user'
  PASSWORD: "MTIzNAo=" # base64 encoded '1234'
  HOST: "bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbAo=" # base64 encoded 'mysql-0.mysql.mysql.svc.cluster.local'