apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  mysql-root-password: "MTIzNAo="      # base64 encoded '1234'
  mysql-user: "dXNlcgo="               # base64 encoded 'user'
  mysql-password: "MTIzNAo="           # base64 encoded '1234'

