apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "MTIzNAo="      # base64 encoded '1234'
  MYSQL_USER: "dXNlcgo="               # base64 encoded 'user'
  MYSQL_PASSWORD: "MTIzNAo="           # base64 encoded '1234'

